_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.0
            "8":
                - 5
            "12": 0.19.0
            "13": darwin-arm64
GAME_URL:
    value: http://localhost:8000/launch_ruffle.html
PORT:
    value: 8000
SAFARI_WEBDRIVER_URL:
    value: http://localhost:4444
down_scaled:
    value:
        height: 160
        width: 200
rollout_steps:
    value: 2046
save_images:
    value: true
timeout_mins:
    value: 1
